adding templates
antonroesler/application-landscape-visualizer pull request #33
Opened 2021-05-03 15:55 UTC by fengyilu

I created 3 different Templates, by adding the extension from GOJS called Figures.JS.
we have to think about, if we should put the template files into a diffrent Js file or not. 
I tried to do this but the problem is that we cannot Export and import variables on the Client side with javascript.

2021-05-03 16:42 UTC, antonroesler requested changes
1. Please remove Figures.js, we cannot publish gojs files on github
2. More comments are needed - the code must be easily understandable by anyone
3. Please add the header from misc/header.txt

2021-05-03 16:42 UTC, antonroesler commented on public/js/index.js
> +
Please use 
```javascript
/**
* Comments to explain what a template is used for and how to use it 
*/
```

2021-05-03 17:40 UTC, antonroesler commented
And also there should be a way to separate the templates into another file.

2021-05-03 18:52 UTC, antonroesler requested changes

2021-05-03 18:52 UTC, antonroesler commented on public/js/templates.js
> +* A short description what this file/class is all about.
Remove this sentence and put the description here. Also make sure the lines are not longer than 80 characters.

2021-05-03 18:52 UTC, antonroesler commented on public/js/templates.js
> +
We still need a comment for every template to ecplain what it it used for:
```javascript
/**
* Template ...
* used for...
*/
```

2021-05-03 18:52 UTC, antonroesler commented on public/js/templates.js
> +
```javascript
/**
* Template ...
* used for...
*/
```

2021-05-03 18:52 UTC, antonroesler commented on public/js/templates.js
> +
```javascript
/**
* Template ...
* used for...
*/
```

2021-05-03 19:50 UTC, antonroesler commented
I have corrected the comments. The comment should be above the function and only describe what our function does, not explain how e.g. a GoJS function works.

2021-05-03 19:52 UTC, antonroesler approved these changes
its ok for now, we may need some more refactoring later

2021-05-03 19:56 UTC, antonroesler commented
Please someone else participate in the approval process!! We always need two people to approve something. Of course, do not simply approve. Please look for errors or otherwise comment and make a request change instead of approve. Only approve if everything is ok. ✌🏻

2021-05-04 06:55 UTC, leo-hsk approved these changes

2021-05-04 06:55 UTC, merged